export const MOVIE_SEAT_REQUEST = 'MOVIE_SEAT_REQUEST'
export const MOVIE_SEAT_SUCCESS = 'MOVIE_SEAT_SUCCESS'
export const MOVIE_SEAT_FAIL = 'MOVIE_SEAT_FAIL'
export const MOVIE_SEAT_BOOKING_SEAT = 'MOVIE_SEAT_BOOKING_SEAT'
export const BOOKING_MOVIE = 'BOOKING_MOVIE'


export const LAY_THONG_TIN_REQUEST = 'LAY_THONG_TIN_REQUEST'
export const LAY_THONG_TIN_SUCCESS = 'LAY_THONG_TIN_SUCCESS'
export const LAY_THONG_TIN_FAIL = 'LAY_THONG_TIN_FAIL'

export const CHANGE_PAGE = 'CHANGE_PAGE'

export const DAT_VE_HOAN_TAT = 'DAT_VE_HOAN_TAT'

export const SEARCH = 'SEARCH'